Integrate maps
MLH-Fellowship/prep-project-4.1.4 pull request #20
Opened 2021-11-19 08:20 UTC by Bhavika-Gianey

fixes: #5 

In Progress
* Changes made *
- Displays current weather location data on a map.

* ToDO *
 - to take the coordinates of the current pin to display weather information.

2021-11-19 15:28 UTC, rajat2502 reviewed
@Bhavika-Gianey looks good to me except the empty spaces thing in some files.

2021-11-19 15:28 UTC, rajat2502 commented on src/components/Map/Map.css
> +
let's remove this

2021-11-22 11:56 UTC, Pratyush1606 approved these changes

2021-11-22 14:18 UTC, NoahCardoza requested changes
Great work, just a few `console.log`'s that I found but that's all!

2021-11-22 14:18 UTC, NoahCardoza commented on src/components/CurrentCityWeather/CurrentCityWeather.js
> +    console.log("city ", addressComponents[0]);
Got a stray console.log here!

2021-11-22 14:18 UTC, NoahCardoza commented on src/components/CurrentCityWeather/CurrentCityWeather.js
> +            console.log(result.name);
And another here.

2021-11-22 14:18 UTC, NoahCardoza commented on src/components/Map/Map.js
> +    console.log(e.latlng);
One more here too.

2021-11-24 00:54 UTC, NoahCardoza requested changes
Looking great so far!

2021-11-24 00:54 UTC, NoahCardoza commented on src/components/CurrentCityWeather/CurrentCityWeather.js
> +    var coordinates = {lat: latitude, lon: longitude};
It's best to use `const` variables wherever possible. When you need the variable to be mutable, `let` is usually better than `var`. To learn more check [this article](https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/) out.

2021-11-24 00:54 UTC, NoahCardoza commented on src/components/CurrentCityWeather/CurrentCityWeather.js
> +          process.env.REACT_APP_APIKEY
While this code works fine, I saw this done recently and have been using it in my own code to make things a little easier:

```suggestion
      "https://api.openweathermap.org/data/2.5/weather?"
      + `lat=${cityCoordinates.lat}&`
      + `lon=${cityCoordinates.lon}&`
      + "units=metric&"
      + `appid=${process.env.REACT_APP_APIKEY}`
```

2021-11-24 12:26 UTC, Bhavika-Gianey commented
@NoahCardoza , I have made the suggested changes and resolved the merge conflicts.
Please review the changes

2021-11-24 16:57 UTC, NoahCardoza approved these changes
LGTM!

2021-11-24 17:33 UTC, NoahCardoza commented
Sorry for the premature "LGTM"! I wrote that after reviewing the code but when I checked the preview, it seems like the marker is still being placed based on the top-left corner. 

After looking through my comments I wonder if I never submitted it... I remember writing it up but maybe I never posted it... 

Basically, when I click, the pin-point of the marker isn't where I clicked, instead the top-left of the marker is placed where I click.

Additionally, while the auto center/zoom is cool, it's a little disorienting, not so much when I'm zoomed out, but when I'm zoomed in and it zooms me out it takes more time to zoom back in just to be zoomed back out again.

Maybe set a threshold so if the user is zoomed in more than 9 points, don't zoom them?

2021-11-24 19:17 UTC, Bhavika-Gianey commented
> Sorry for the premature "LGTM"! I wrote that after reviewing the code but when I checked the preview, it seems like the marker is still being placed based on the top-left corner.
> 
> After looking through my comments I wonder if I never submitted it... I remember writing it up but maybe I never posted it...
> 
> Basically, when I click, the pin-point of the marker isn't where I clicked, instead the top-left of the marker is placed where I click.
> 
> Additionally, while the auto center/zoom is cool, it's a little disorienting, not so much when I'm zoomed out, but when I'm zoomed in and it zooms me out it takes more time to zoom back in just to be zoomed back out again.
> 
> Maybe set a threshold so if the user is zoomed in more than 9 points, don't zoom them?

Did the changes.
Please review again.

2021-11-25 08:44 UTC, NoahCardoza commented
It seems the map is still zooming out when I am up close and click. Also another merge conflict 😭  I'll try to get this merged in first thing tomorrow morning. If you'd like to start working on another PR while you wait for me go ahead!

2021-11-25 13:02 UTC, Pratyush1606 approved these changes

2021-11-25 13:57 UTC, Bhavika-Gianey commented
> It seems the map is still zooming out when I am up close and click. Also another merge conflict 😭 I'll try to get this merged in first thing tomorrow morning. If you'd like to start working on another PR while you wait for me go ahead!

I changed the max zoom-in property. The map will now only be zoomed-in upon change of marker position. The merge conflicts are also resolved 🥵.

2021-11-26 14:02 UTC, NoahCardoza commented
LGTM!

2021-11-26 14:03 UTC, merged